sudo: required
dist: trusty
group: edge
addons:
  apt:
    sources:
      - chef-current-trusty
    packages:
      - chefdk
install: echo "skip bundle install"
branches:
  only:
    - master
script:
  - bin/rake chef:build && cd pkg/poise-service-aix*
  - cookstyle
  - foodcritic . --exclude spec -f any
